[2024-02-18T13:18:53.026+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline.step_2_copy_mapper scheduled__2024-02-17T01:01:58.985022+00:00 [queued]>
[2024-02-18T13:18:53.039+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline.step_2_copy_mapper scheduled__2024-02-17T01:01:58.985022+00:00 [queued]>
[2024-02-18T13:18:53.039+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-18T13:18:53.079+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): step_2_copy_mapper> on 2024-02-17 01:01:58.985022+00:00
[2024-02-18T13:18:53.085+0000] {standard_task_runner.py:60} INFO - Started process 2082 to run task
[2024-02-18T13:18:53.094+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'HADOOP_ELT_pipeline', 'step_2_copy_mapper', 'scheduled__2024-02-17T01:01:58.985022+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/ELT_automated_airflow.py', '--cfg-path', '/tmp/tmp2cmvlwws']
[2024-02-18T13:18:53.106+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask step_2_copy_mapper
[2024-02-18T13:18:53.228+0000] {task_command.py:423} INFO - Running <TaskInstance: HADOOP_ELT_pipeline.step_2_copy_mapper scheduled__2024-02-17T01:01:58.985022+00:00 [running]> on host 8bb8949050c9
[2024-02-18T13:18:53.421+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='HADOOP_ELT_pipeline' AIRFLOW_CTX_TASK_ID='step_2_copy_mapper' AIRFLOW_CTX_EXECUTION_DATE='2024-02-17T01:01:58.985022+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-17T01:01:58.985022+00:00'
[2024-02-18T13:18:53.441+0000] {logging_mixin.py:188} INFO - Error occurred: Command 'hadoop fs -put C:\Users\LENOVO\ETL-and-ELT-integration-pipelines\mapper.py /python' returned non-zero exit status 127.
[2024-02-18T13:18:53.442+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-18T13:18:53.458+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=HADOOP_ELT_pipeline, task_id=step_2_copy_mapper, execution_date=20240217T010158, start_date=20240218T131853, end_date=20240218T131853
[2024-02-18T13:18:53.543+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-18T13:18:53.571+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
