[2024-02-17T01:02:44.475+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline.step_1_load_data manual__2024-02-17T01:02:26.982234+00:00 [queued]>
[2024-02-17T01:02:44.604+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline.step_1_load_data manual__2024-02-17T01:02:26.982234+00:00 [queued]>
[2024-02-17T01:02:44.608+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-17T01:02:44.744+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): step_1_load_data> on 2024-02-17 01:02:26.982234+00:00
[2024-02-17T01:02:44.758+0000] {standard_task_runner.py:60} INFO - Started process 168 to run task
[2024-02-17T01:02:44.763+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'HADOOP_ELT_pipeline', 'step_1_load_data', 'manual__2024-02-17T01:02:26.982234+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/ELT_automated_airflow.py', '--cfg-path', '/tmp/tmp6mxr5kzi']
[2024-02-17T01:02:44.775+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask step_1_load_data
[2024-02-17T01:02:45.298+0000] {task_command.py:423} INFO - Running <TaskInstance: HADOOP_ELT_pipeline.step_1_load_data manual__2024-02-17T01:02:26.982234+00:00 [running]> on host 8bb8949050c9
[2024-02-17T01:02:45.909+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='HADOOP_ELT_pipeline' AIRFLOW_CTX_TASK_ID='step_1_load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-17T01:02:26.982234+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-17T01:02:26.982234+00:00'
[2024-02-17T01:02:45.941+0000] {logging_mixin.py:188} INFO - Error occurred: Command 'hadoop fs -copyFromLocal C:\Users\LENOVO\ETL-and-ELT-integration-pipelines\sales_csv /sales_data' returned non-zero exit status 127.
[2024-02-17T01:02:45.943+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-17T01:02:46.001+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=HADOOP_ELT_pipeline, task_id=step_1_load_data, execution_date=20240217T010226, start_date=20240217T010244, end_date=20240217T010246
[2024-02-17T01:02:46.119+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-17T01:02:46.290+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
