[2024-02-16T22:23:07.611+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline_.step_1_load_data manual__2024-02-16T22:22:59.981887+00:00 [queued]>
[2024-02-16T22:23:07.630+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline_.step_1_load_data manual__2024-02-16T22:22:59.981887+00:00 [queued]>
[2024-02-16T22:23:07.631+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-16T22:23:07.683+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): step_1_load_data> on 2024-02-16 22:22:59.981887+00:00
[2024-02-16T22:23:07.689+0000] {standard_task_runner.py:60} INFO - Started process 311 to run task
[2024-02-16T22:23:07.694+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'HADOOP_ELT_pipeline_', 'step_1_load_data', 'manual__2024-02-16T22:22:59.981887+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/ELT_automated_airflow.py', '--cfg-path', '/tmp/tmp9od7jqkg']
[2024-02-16T22:23:07.698+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask step_1_load_data
[2024-02-16T22:23:07.825+0000] {task_command.py:423} INFO - Running <TaskInstance: HADOOP_ELT_pipeline_.step_1_load_data manual__2024-02-16T22:22:59.981887+00:00 [running]> on host a1bb76e936e6
[2024-02-16T22:23:07.990+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='HADOOP_ELT_pipeline_' AIRFLOW_CTX_TASK_ID='step_1_load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-16T22:22:59.981887+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-16T22:22:59.981887+00:00'
[2024-02-16T22:23:08.002+0000] {logging_mixin.py:188} INFO - Error occurred: Command 'hadoop fs -copyFromLocal C:\Users\LENOVO\ETL-and-ELT-integration-pipelines\sales_csv /sales_data' returned non-zero exit status 127.
[2024-02-16T22:23:08.003+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-16T22:23:08.019+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=HADOOP_ELT_pipeline_, task_id=step_1_load_data, execution_date=20240216T222259, start_date=20240216T222307, end_date=20240216T222308
[2024-02-16T22:23:08.069+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-16T22:23:08.129+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
