[2024-02-16T22:13:32.028+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline.step_1_load_data manual__2024-02-16T22:13:26.993462+00:00 [queued]>
[2024-02-16T22:13:32.047+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline.step_1_load_data manual__2024-02-16T22:13:26.993462+00:00 [queued]>
[2024-02-16T22:13:32.048+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-16T22:13:32.093+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): step_1_load_data> on 2024-02-16 22:13:26.993462+00:00
[2024-02-16T22:13:32.099+0000] {standard_task_runner.py:60} INFO - Started process 230 to run task
[2024-02-16T22:13:32.107+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'HADOOP_ELT_pipeline', 'step_1_load_data', 'manual__2024-02-16T22:13:26.993462+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ELT_automated_airflow.py', '--cfg-path', '/tmp/tmp3lfrrisl']
[2024-02-16T22:13:32.110+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask step_1_load_data
[2024-02-16T22:13:32.223+0000] {task_command.py:423} INFO - Running <TaskInstance: HADOOP_ELT_pipeline.step_1_load_data manual__2024-02-16T22:13:26.993462+00:00 [running]> on host a1bb76e936e6
[2024-02-16T22:13:32.374+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='HADOOP_ELT_pipeline' AIRFLOW_CTX_TASK_ID='step_1_load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-16T22:13:26.993462+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-16T22:13:26.993462+00:00'
[2024-02-16T22:13:32.382+0000] {logging_mixin.py:188} INFO - Error occurred: Command 'hadoop fs -copyFromLocal C:\Users\LENOVO\ETL-and-ELT-integration-pipelines\sales_csv /sales_data' returned non-zero exit status 127.
[2024-02-16T22:13:32.383+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-16T22:13:32.397+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=HADOOP_ELT_pipeline, task_id=step_1_load_data, execution_date=20240216T221326, start_date=20240216T221332, end_date=20240216T221332
[2024-02-16T22:13:32.442+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-16T22:13:32.488+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
