[2024-02-16T23:06:42.295+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline_FINAL.step_2_copy_mapper manual__2024-02-16T23:06:32.134992+00:00 [queued]>
[2024-02-16T23:06:42.313+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline_FINAL.step_2_copy_mapper manual__2024-02-16T23:06:32.134992+00:00 [queued]>
[2024-02-16T23:06:42.313+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-16T23:06:42.368+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): step_2_copy_mapper> on 2024-02-16 23:06:32.134992+00:00
[2024-02-16T23:06:42.381+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'HADOOP_ELT_pipeline_FINAL', 'step_2_copy_mapper', 'manual__2024-02-16T23:06:32.134992+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/ELT_automated_airflow.py', '--cfg-path', '/tmp/tmpelu0az2o']
[2024-02-16T23:06:42.375+0000] {standard_task_runner.py:60} INFO - Started process 907 to run task
[2024-02-16T23:06:42.384+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask step_2_copy_mapper
[2024-02-16T23:06:42.524+0000] {task_command.py:423} INFO - Running <TaskInstance: HADOOP_ELT_pipeline_FINAL.step_2_copy_mapper manual__2024-02-16T23:06:32.134992+00:00 [running]> on host a1bb76e936e6
[2024-02-16T23:06:42.744+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='HADOOP_ELT_pipeline_FINAL' AIRFLOW_CTX_TASK_ID='step_2_copy_mapper' AIRFLOW_CTX_EXECUTION_DATE='2024-02-16T23:06:32.134992+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-16T23:06:32.134992+00:00'
[2024-02-16T23:06:42.769+0000] {logging_mixin.py:188} INFO - Error occurred: Command 'hadoop fs -put C:\Users\LENOVO\ETL-and-ELT-integration-pipelines\mapper.py /python' returned non-zero exit status 127.
[2024-02-16T23:06:42.771+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-16T23:06:42.790+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=HADOOP_ELT_pipeline_FINAL, task_id=step_2_copy_mapper, execution_date=20240216T230632, start_date=20240216T230642, end_date=20240216T230642
[2024-02-16T23:06:42.843+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-16T23:06:42.899+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
