[2024-02-16T22:33:53.275+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline.step_2_copy_mapper manual__2024-02-16T22:33:43.665167+00:00 [queued]>
[2024-02-16T22:33:53.289+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline.step_2_copy_mapper manual__2024-02-16T22:33:43.665167+00:00 [queued]>
[2024-02-16T22:33:53.290+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-16T22:33:53.329+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): step_2_copy_mapper> on 2024-02-16 22:33:43.665167+00:00
[2024-02-16T22:33:53.333+0000] {standard_task_runner.py:60} INFO - Started process 452 to run task
[2024-02-16T22:33:53.338+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'HADOOP_ELT_pipeline', 'step_2_copy_mapper', 'manual__2024-02-16T22:33:43.665167+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/ELT_automated_airflow.py', '--cfg-path', '/tmp/tmp4y6uj3_e']
[2024-02-16T22:33:53.340+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask step_2_copy_mapper
[2024-02-16T22:33:53.457+0000] {task_command.py:423} INFO - Running <TaskInstance: HADOOP_ELT_pipeline.step_2_copy_mapper manual__2024-02-16T22:33:43.665167+00:00 [running]> on host a1bb76e936e6
[2024-02-16T22:33:53.611+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='HADOOP_ELT_pipeline' AIRFLOW_CTX_TASK_ID='step_2_copy_mapper' AIRFLOW_CTX_EXECUTION_DATE='2024-02-16T22:33:43.665167+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-16T22:33:43.665167+00:00'
[2024-02-16T22:33:53.620+0000] {logging_mixin.py:188} INFO - Error occurred: Command 'hadoop fs -put C:\Users\LENOVO\ETL-and-ELT-integration-pipelines\mapper.py /python' returned non-zero exit status 127.
[2024-02-16T22:33:53.621+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-16T22:33:53.637+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=HADOOP_ELT_pipeline, task_id=step_2_copy_mapper, execution_date=20240216T223343, start_date=20240216T223353, end_date=20240216T223353
[2024-02-16T22:33:53.714+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-16T22:33:53.747+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
